version: '3.8'

services:
  web:
    image: rust:1.91
    container_name: pcs_web
    # 自动把当前目录挂载进去
    volumes:
      - .:/app
      - ./config.toml:/app/config.toml:ro
    working_dir: /app
    ports:
      - "5200:5200"
    # 环境变量配置
    # 注意：如果需要使用代理，可以通过环境变量设置，例如：
    # - http_proxy=http://proxy.example.com:8080
    # - https_proxy=http://proxy.example.com:8080
    environment:
      - PORT=5200
    # 容器启动后自动安装依赖并运行 Web 服务器
    command: >
      bash -c "apt-get update && apt-get install -y pkg-config libssl-dev && cargo run --release --bin baidu-direct-link-web"

