version: '3.8'

services:
  app:
    image: rust:1.91
    container_name: pcs_dev
    # 自动把当前目录挂载进去
    volumes:
      - .:/app
      - ./config.toml:/app/config.toml:ro
    working_dir: /app
    ports:
      - "5200:5200"
    # 环境变量配置
    # 注意：如果需要使用代理，可以通过环境变量设置
    environment:
      # 代理设置（如果需要，取消注释并修改）
      # - http_proxy=http://proxy.example.com:8080
      # - https_proxy=http://proxy.example.com:8080
      # - HTTP_PROXY=http://proxy.example.com:8080
      # - HTTPS_PROXY=http://proxy.example.com:8080
      # - no_proxy=localhost,127.0.0.1,::1
    # 容器启动后自动安装依赖并运行
    # 注意：这里把 apt install 和 cargo run 连起来了
    # 命令行参数可以通过 docker-compose run 传递，例如：
    # podman-compose run --rm app "https://pan.baidu.com/s/1xxxxx" "提取码"
    # 注意：docker-compose run 时，后面的参数会替换 command，所以需要这样使用：
    # podman-compose run --rm app bash -c "apt-get update && apt-get install -y pkg-config libssl-dev && cargo run --release -- \"$@\"" -- "https://pan.baidu.com/s/1xxxxx" "提取码"
    command: >
      bash -c "apt-get update && apt-get install -y pkg-config libssl-dev && cargo run --release"
    # 使用 podman 的 rootless 模式
    # 如果需要 root 权限，可以移除 user 配置
    # user: "${UID:-1000}:${GID:-1000}"

